/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'
import { Route as AuthenticatedCotizacionRouteImport } from './routes/_authenticated/cotizacion'
import { Route as AuthenticatedCotizacionesRouteImport } from './routes/_authenticated/cotizaciones'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPromocionesRouteImport } from './routes/_authenticated/promociones'
import { Route as AuthenticatedRecursosRouteImport } from './routes/_authenticated/recursos'
import { Route as AuthenticatedVentasRouteImport } from './routes/_authenticated/ventas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotizacionRoute = AuthenticatedCotizacionRouteImport.update({
  id: '/cotizacion',
  path: '/cotizacion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotizacionesRoute =
  AuthenticatedCotizacionesRouteImport.update({
    id: '/cotizaciones',
    path: '/cotizaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromocionesRoute =
  AuthenticatedPromocionesRouteImport.update({
    id: '/promociones',
    path: '/promociones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecursosRoute = AuthenticatedRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentasRoute = AuthenticatedVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/cotizacion': typeof AuthenticatedCotizacionRoute
  '/cotizaciones': typeof AuthenticatedCotizacionesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/promociones': typeof AuthenticatedPromocionesRoute
  '/recursos': typeof AuthenticatedRecursosRoute
  '/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/cotizacion': typeof AuthenticatedCotizacionRoute
  '/cotizaciones': typeof AuthenticatedCotizacionesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/promociones': typeof AuthenticatedPromocionesRoute
  '/recursos': typeof AuthenticatedRecursosRoute
  '/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/cotizacion': typeof AuthenticatedCotizacionRoute
  '/_authenticated/cotizaciones': typeof AuthenticatedCotizacionesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/promociones': typeof AuthenticatedPromocionesRoute
  '/_authenticated/recursos': typeof AuthenticatedRecursosRoute
  '/_authenticated/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/admin'
    | '/catalogo'
    | '/cotizacion'
    | '/cotizaciones'
    | '/dashboard'
    | '/favoritos'
    | '/pedidos'
    | '/perfil'
    | '/promociones'
    | '/recursos'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/admin'
    | '/catalogo'
    | '/cotizacion'
    | '/cotizaciones'
    | '/dashboard'
    | '/favoritos'
    | '/pedidos'
    | '/perfil'
    | '/promociones'
    | '/recursos'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/catalogo'
    | '/_authenticated/cotizacion'
    | '/_authenticated/cotizaciones'
    | '/_authenticated/dashboard'
    | '/_authenticated/favoritos'
    | '/_authenticated/pedidos'
    | '/_authenticated/perfil'
    | '/_authenticated/promociones'
    | '/_authenticated/recursos'
    | '/_authenticated/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotizacion': {
      id: '/_authenticated/cotizacion'
      path: '/cotizacion'
      fullPath: '/cotizacion'
      preLoaderRoute: typeof AuthenticatedCotizacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotizaciones': {
      id: '/_authenticated/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof AuthenticatedCotizacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promociones': {
      id: '/_authenticated/promociones'
      path: '/promociones'
      fullPath: '/promociones'
      preLoaderRoute: typeof AuthenticatedPromocionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recursos': {
      id: '/_authenticated/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof AuthenticatedRecursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas': {
      id: '/_authenticated/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthenticatedVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedCotizacionRoute: typeof AuthenticatedCotizacionRoute
  AuthenticatedCotizacionesRoute: typeof AuthenticatedCotizacionesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPromocionesRoute: typeof AuthenticatedPromocionesRoute
  AuthenticatedRecursosRoute: typeof AuthenticatedRecursosRoute
  AuthenticatedVentasRoute: typeof AuthenticatedVentasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedCotizacionRoute: AuthenticatedCotizacionRoute,
  AuthenticatedCotizacionesRoute: AuthenticatedCotizacionesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPromocionesRoute: AuthenticatedPromocionesRoute,
  AuthenticatedRecursosRoute: AuthenticatedRecursosRoute,
  AuthenticatedVentasRoute: AuthenticatedVentasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
